### ISSUE TITLE
无法运行！！ Starting MariaDB database server mysqld ...fail!

### ISSUE THREAD

**Issue by cszs1986** [lvxj11/docker#11]
Starting MariaDB database server mysqld
...fail!

挂载后无法运行
/mnt/user/appdata/erpnext/mysql
/mnt/user/appdata/erpnext/frappe

不挂载可以运行

**Comment by lvxj11** [comment]
信息太少无法判断，看看是不是权限的问题

**Comment by lvxj11** [comment]
太久了，抱歉，先关闭吧。
