### ISSUE TITLE
site1.local does not exist

### ISSUE THREAD

**Issue by improve100** [lvxj11/docker#13]
Not Found
site1.local does not exist

**Comment by tangyanglai** [comment]
我也遇到了这个问题，想问下需要怎么处理。
命令：
docker run -itd -p 80:80 \
  -v erpnext14_db:/var/lib/mysql \
  -v erpnext14_sites:/home/frappe/frappe-bench/sites \
  --name erpnext-14 lvxj11/erpnext:14.11.0
