### ISSUE TITLE
docker版ERPNext14升ERPNext15的数据备份和恢复问题

### ISSUE THREAD

**Issue by tobchef** [lvxj11/docker#14]
大佬erpnext的docker虽然做了数据卷的持久化，但是在v14升级到v15时，直接复制数据卷会出错。
我也是遇到此问题摸索了好久，才找到V14升V15时数据备份和恢复的方法，其实就是使用erpnext的官方备份和恢复功能：

1、首先确保erpnext14的docker是正常运行的，进入容器的命令行，如果你是用群晖或docker desktop可省略这步直接进入终端机：
```
docker exec -it ERPNext14 bash
```
此处的“ERPNext14”是我的ERPNext14的容器名，你的如果不一样记得修改

2、备份所有站点：
```
bench backup-all-sites
```

执行后的结果如下，我们主要是需要.sql.gz 的数据备份：
```
Backup Summary for site1.local at 2023-12-18 14:09:16.675691
Config  : ./site1.local/private/backups/20231218_140915-site1_local-site_config_backup.json 86.0B
Database: ./site1.local/private/backups/20231218_140915-site1_local-database.sql.gz         1.1MiB
```

3、关闭ERPNext14容器，新建ERPNext15容器并运行，再次进入容器的命令行/终端机：
```
docker exec -it ERPNext bash
```
此处的“ERPNext”是我的ERPNext15的容器名，你的如果不一样记得修改

4、将第2步备份的ERPNext14数据文件复制到ERPNext15的目录，然后恢复站点数据：
```
bench restore ./site1.local/private/backups/20231218_140915-site1_local-database.sql.gz
```
这里会提示输入MYSQL数据库密码，默认是“Pass1234”

5、恢复完成后需要执行数据迁移，将V14数据升级为V15，才能正常使用
```
bench migrate
bench restart
```

这样应该就顺利完成ERPNext v14到v15的升级了。

**Comment by lvxj11** [comment]
跨版本升级数据必定是要处理的。docker方式升级和手动还不太一样，升级镜像后直接连接旧版数据库一定会出问题，需要手动迁移。参考@tobchef 的方法。
