### ISSUE TITLE
Docker部署后，访问网页，报错Not Found site1.local does not exist

### ISSUE THREAD

**Issue by tangyanglai** [lvxj11/docker#15]
命令：
docker run -itd -p 80:80
-v erpnext14_db:/var/lib/mysql
-v erpnext14_sites:/home/frappe/frappe-bench/sites
--name erpnext-14 lvxj11/erpnext:14.11.0

**Comment by lvxj11** [comment]
需要用卷挂载，不能用路径挂载。
