### ISSUE TITLE
宿主机的绝对路径site1.local does not exist

### ISSUE THREAD

**Issue by improve100** [lvxj11/docker#16]
docker run -itd -p 80:80 \
-v /srv/erpnext14_db:/var/lib/mysql \
-v /srv/erpnext14_sites:/home/frappe/frappe-bench/sites \
--name erpnext-14 lvxj11/erpnext:latest
改成绝对路径就不能用

**Comment by lvxj11** [comment]
不能用路径挂载，自能用卷挂载。容器镜像说明里有原因。
