### ISSUE TITLE
erpnext15/install-erpnext15.sh  安装wkhtmltopdf失败

### ISSUE THREAD

**Issue by biga-bomb** [lvxj11/docker#17]
+ 在构建erpnext15镜像时，在打印以下内容后退出
`==========已存在wkhtmltox，但不是推荐的0.12.6版本。==========`
`wkhtmltopdf: error while loading shared libraries: libQt5Core.so.5: cannot open shared object file: No such file or directory`

+ 解决方法
![image](https://github.com/lvxj11/docker/assets/32594192/b4aee02e-9ca8-4259-a425-1a3a1c90c82a)
即添加以下内容
`strip --remove-section=.note.ABI-tag /usr/lib/x86_64-linux-gnu/libQt5Core.so.5`

+ 参考链接
[https://discussions.eramba.org/t/question-wkhtmltopdf-error-in-docker-installation-on-centos-7/2428/4](url)

+ 但最终构建镜像还是失败了:(
+ 已使用了您docker hub的最新镜像，非常nice，求问docker hub里最新的镜像是如何生成的？

**Comment by lvxj11** [comment]
脚本只在Ubuntu22.04纯净版下测试过。事实上后期我自己只用在生成镜像上。偶尔会有群友使用安装。

镜像生成就简单了，拉取文件夹，进erpnext15目录直接build就行了。
